find_package(GTest QUIET)
if(NOT GTest_FOUND)
    include(FetchContent)
    FetchContent_Declare(googletest
            URL https://github.com/google/googletest/archive/refs/tags/v1.14.0.zip)
    set(gtest_force_shared_crt ON CACHE BOOL "" FORCE)
    FetchContent_MakeAvailable(googletest)
    add_library(GTest::GTest ALIAS gtest)
    add_library(GTest::Main ALIAS gtest_main)
endif()

macro(make_units_test name)
    add_executable(${name} utl/${name}.cpp)
    target_link_libraries(${name} utl::utl GTest::GTest GTest::Main)
    utl_apply_warnings(${name})
    add_test(NAME ${name} COMMAND ${name})
endmacro()

make_units_test(t_base_amount_of_substance)
make_units_test(t_base_electric_current)
make_units_test(t_base_length)
make_units_test(t_base_luminous_intensity)
make_units_test(t_base_mass)
make_units_test(t_base_thermodynamic_temperature)
make_units_test(t_base_time)
make_units_test(t_base_unit)

make_units_test(t_derived_absorbed_dose)
make_units_test(t_derived_acceleration)
make_units_test(t_derived_activity)
make_units_test(t_derived_angle)
make_units_test(t_derived_area)
make_units_test(t_derived_capacitance)
make_units_test(t_derived_catalytic_activity)
make_units_test(t_derived_conductance)
make_units_test(t_derived_dose_equivalent)
make_units_test(t_derived_electric_charge)
make_units_test(t_derived_energy)
make_units_test(t_derived_force)
make_units_test(t_derived_frequency)
make_units_test(t_derived_illuminance)
make_units_test(t_derived_inductance)
make_units_test(t_derived_luminous_flux)
make_units_test(t_derived_magnetic_flux)
make_units_test(t_derived_magnetic_flux_density)
make_units_test(t_derived_power)
make_units_test(t_derived_pressure)
make_units_test(t_derived_resistance)
make_units_test(t_derived_solid_angle)
make_units_test(t_derived_velocity)
make_units_test(t_derived_voltage)
make_units_test(t_derived_volume)

make_units_test(t_mixed_precision)
make_units_test(t_temperature_delta)
make_units_test(t_angle_dimension)
make_units_test(t_operators)
make_units_test(t_ux)
make_units_test(t_constexpr)
make_units_test(t_math)
make_units_test(t_property)

add_executable(t_odr utl/t_odr_main.cpp utl/t_odr_second.cpp)
target_link_libraries(t_odr utl::utl GTest::GTest)
utl_apply_warnings(t_odr)
add_test(NAME t_odr COMMAND t_odr)
