/*
 * Copyright (C) 2024 Adam Ligocki
 * Distributed under MIT licence
 *
 * Single-header amalgamation of <utl/utl.hpp>, generated by
 * tools/amalgamate.py. Do not edit by hand; regenerate instead.
 */

#pragma once

#include <array>
#include <cmath>
#include <cstddef>
#include <cstdint>
#include <type_traits>

// https://www.nist.gov/pml/owm/metric-si/si-units

namespace utl {

    constexpr double PI = 3.14159265358979323846;

    constexpr double DECA = 1e1;
    constexpr double HECTO = 1e2;
    constexpr double KILO = 1e3;
    constexpr double MEGA = 1e6;
    constexpr double GIGA = 1e9;
    constexpr double TERA = 1e12;
    constexpr double PETA = 1e15;
    constexpr double EXA = 1e18;
    constexpr double ZETTA = 1e21;
    constexpr double YOTTA = 1e24;
    constexpr double RONNA = 1e27;
    constexpr double QUETTA = 1e30;

    constexpr double DECI = 1e-1;
    constexpr double CENTI = 1e-2;
    constexpr double MILLI = 1e-3;
    constexpr double MICRO = 1e-6;
    constexpr double NANO = 1e-9;
    constexpr double PICO = 1e-12;
    constexpr double FEMTO = 1e-15;
    constexpr double ATTO = 1e-18;
    constexpr double ZEPTO = 1e-21;
    constexpr double YOCTO = 1e-24;
    constexpr double RONTO = 1e-27;
    constexpr double QUECTO = 1e-30;

    constexpr double SECS_IN_MINUTE = 60.0;
    constexpr double MINUTES_IN_HOUR = 60.0;
    constexpr double HOURS_IN_DAY = 24.0;
    constexpr double DAYS_IN_YEAR = 365.0;
} // namespace utl

namespace utl {

    template<class UnitType>
    struct UnitMapper {
    };

    template<class UnitType, class = void>
    struct MappedUnit {
        using type = UnitType;
    };

    template<class UnitType>
    struct MappedUnit<UnitType, std::void_t<typename UnitMapper<UnitType>::type>> {
        using type = typename UnitMapper<UnitType>::type;
    };

    template<class UnitType>
    using mapped_unit_t = typename MappedUnit<UnitType>::type;

    constexpr auto same_dim(const std::array<int8_t, 8> &lhs, const std::array<int8_t, 8> &rhs) -> bool {
        for (std::size_t i = 0; i < lhs.size(); ++i) {
            if (lhs[i] != rhs[i]) {
                return false;
            }
        }
        return true;
    }

    template<typename T, int8_t TIME, int8_t LENGTH, int8_t MASS, int8_t EL_CURR, int8_t TD_TEMP, int8_t AM_OF_SUB, int8_t LUM_INT, int8_t ANGLE = 0>
    class BaseUnit {
        using Self = BaseUnit<T, TIME, LENGTH, MASS, EL_CURR, TD_TEMP, AM_OF_SUB, LUM_INT, ANGLE>;
        using SelfInv = BaseUnit<T, -TIME, -LENGTH, -MASS, -EL_CURR, -TD_TEMP, -AM_OF_SUB, -LUM_INT, -ANGLE>;
    public:
        BaseUnit() = delete;

        constexpr explicit BaseUnit(const T &value) : value_{value} {};

        [[nodiscard]] static constexpr std::array<int8_t, 8> dim() {
            return {TIME, LENGTH, MASS, EL_CURR, TD_TEMP, AM_OF_SUB, LUM_INT, ANGLE};
        }

        static constexpr int8_t TimeDim() { return TIME; };
        static constexpr int8_t LengthDim() { return LENGTH; };
        static constexpr int8_t MassDim() { return MASS; };
        static constexpr int8_t ElCurrDim() { return EL_CURR; };
        static constexpr int8_t TdTempDim() { return TD_TEMP; };
        static constexpr int8_t AmOfSubDim() { return AM_OF_SUB; };
        static constexpr int8_t LumIntDim() { return LUM_INT; };
        static constexpr int8_t AngleDim() { return ANGLE; };

        constexpr auto value() const -> const T & {
            return value_;
        }

        constexpr void set_value(const T &val) {
            value_ = val;
        }

        constexpr auto raw() const -> Self {
            return *this;
        }

        constexpr auto inv() const -> SelfInv {
            return SelfInv{
                static_cast<T>(1.0) / value_};
        }

        template<typename UnitType = Self>
        constexpr typename UnitMapper<UnitType>::type type() const {
            return typename UnitMapper<UnitType>::type(this->value_);
        }

        template<typename U, int8_t TIME2, int8_t LENGTH2, int8_t MASS2, int8_t EL_CURR2, int8_t TD_TEMP2, int8_t AM_OF_SUB2, int8_t LUM_INT2, int8_t ANGLE2>
        constexpr auto operator+(const BaseUnit<U, TIME2, LENGTH2, MASS2, EL_CURR2, TD_TEMP2, AM_OF_SUB2, LUM_INT2, ANGLE2> &other) const -> mapped_unit_t<BaseUnit<std::common_type_t<T, U>, TIME, LENGTH, MASS, EL_CURR, TD_TEMP, AM_OF_SUB, LUM_INT, ANGLE>> {
            static_assert(same_dim(dim(), std::decay_t<decltype(other)>::dim()), "utl: cannot add quantities of different dimensions");
            using Result = mapped_unit_t<BaseUnit<std::common_type_t<T, U>, TIME, LENGTH, MASS, EL_CURR, TD_TEMP, AM_OF_SUB, LUM_INT, ANGLE>>;
            return Result(value_ + other.value());
        }

        template<typename U, int8_t TIME2, int8_t LENGTH2, int8_t MASS2, int8_t EL_CURR2, int8_t TD_TEMP2, int8_t AM_OF_SUB2, int8_t LUM_INT2, int8_t ANGLE2>
        constexpr auto operator-(const BaseUnit<U, TIME2, LENGTH2, MASS2, EL_CURR2, TD_TEMP2, AM_OF_SUB2, LUM_INT2, ANGLE2> &other) const -> mapped_unit_t<BaseUnit<std::common_type_t<T, U>, TIME, LENGTH, MASS, EL_CURR, TD_TEMP, AM_OF_SUB, LUM_INT, ANGLE>> {
            static_assert(same_dim(dim(), std::decay_t<decltype(other)>::dim()), "utl: cannot subtract quantities of different dimensions");
            using Result = mapped_unit_t<BaseUnit<std::common_type_t<T, U>, TIME, LENGTH, MASS, EL_CURR, TD_TEMP, AM_OF_SUB, LUM_INT, ANGLE>>;
            return Result(value_ - other.value());
        }

        constexpr auto operator*(T scalar) const -> mapped_unit_t<Self> {
            return mapped_unit_t<Self>(value() * scalar);
        }

        constexpr auto operator/(T scalar) const -> mapped_unit_t<Self> {
            return mapped_unit_t<Self>(value() / scalar);
        }

        friend constexpr auto operator*(T lhs, const Self &rhs) -> mapped_unit_t<Self> {
            return mapped_unit_t<Self>(rhs.value() * lhs);
        }

        constexpr auto operator-() const -> mapped_unit_t<Self> {
            return mapped_unit_t<Self>(-value_);
        }

        constexpr auto operator+=(const BaseUnit &other) -> BaseUnit & {
            value_ += other.value_;
            return *this;
        }

        constexpr auto operator-=(const BaseUnit &other) -> BaseUnit & {
            value_ -= other.value_;
            return *this;
        }

        constexpr auto operator*=(T scalar) -> BaseUnit & {
            value_ *= scalar;
            return *this;
        }

        constexpr auto operator/=(T scalar) -> BaseUnit & {
            value_ /= scalar;
            return *this;
        }

        template<typename U, int8_t TIME2, int8_t LENGTH2, int8_t MASS2, int8_t EL_CURR2, int8_t TD_TEMP2, int8_t AM_OF_SUB2, int8_t LUM_INT2, int8_t ANGLE2>
        constexpr auto operator==(const BaseUnit<U, TIME2, LENGTH2, MASS2, EL_CURR2, TD_TEMP2, AM_OF_SUB2, LUM_INT2, ANGLE2> &other) const -> bool {
            static_assert(same_dim(dim(), std::decay_t<decltype(other)>::dim()), "utl: cannot compare quantities of different dimensions");
            return value_ == other.value();
        }

        template<typename U, int8_t TIME2, int8_t LENGTH2, int8_t MASS2, int8_t EL_CURR2, int8_t TD_TEMP2, int8_t AM_OF_SUB2, int8_t LUM_INT2, int8_t ANGLE2>
        constexpr auto operator!=(const BaseUnit<U, TIME2, LENGTH2, MASS2, EL_CURR2, TD_TEMP2, AM_OF_SUB2, LUM_INT2, ANGLE2> &other) const -> bool {
            static_assert(same_dim(dim(), std::decay_t<decltype(other)>::dim()), "utl: cannot compare quantities of different dimensions");
            return value_ != other.value();
        }

        template<typename U, int8_t TIME2, int8_t LENGTH2, int8_t MASS2, int8_t EL_CURR2, int8_t TD_TEMP2, int8_t AM_OF_SUB2, int8_t LUM_INT2, int8_t ANGLE2>
        constexpr auto operator<(const BaseUnit<U, TIME2, LENGTH2, MASS2, EL_CURR2, TD_TEMP2, AM_OF_SUB2, LUM_INT2, ANGLE2> &other) const -> bool {
            static_assert(same_dim(dim(), std::decay_t<decltype(other)>::dim()), "utl: cannot compare quantities of different dimensions");
            return value_ < other.value();
        }

        template<typename U, int8_t TIME2, int8_t LENGTH2, int8_t MASS2, int8_t EL_CURR2, int8_t TD_TEMP2, int8_t AM_OF_SUB2, int8_t LUM_INT2, int8_t ANGLE2>
        constexpr auto operator<=(const BaseUnit<U, TIME2, LENGTH2, MASS2, EL_CURR2, TD_TEMP2, AM_OF_SUB2, LUM_INT2, ANGLE2> &other) const -> bool {
            static_assert(same_dim(dim(), std::decay_t<decltype(other)>::dim()), "utl: cannot compare quantities of different dimensions");
            return value_ <= other.value();
        }

        template<typename U, int8_t TIME2, int8_t LENGTH2, int8_t MASS2, int8_t EL_CURR2, int8_t TD_TEMP2, int8_t AM_OF_SUB2, int8_t LUM_INT2, int8_t ANGLE2>
        constexpr auto operator>(const BaseUnit<U, TIME2, LENGTH2, MASS2, EL_CURR2, TD_TEMP2, AM_OF_SUB2, LUM_INT2, ANGLE2> &other) const -> bool {
            static_assert(same_dim(dim(), std::decay_t<decltype(other)>::dim()), "utl: cannot compare quantities of different dimensions");
            return value_ > other.value();
        }

        template<typename U, int8_t TIME2, int8_t LENGTH2, int8_t MASS2, int8_t EL_CURR2, int8_t TD_TEMP2, int8_t AM_OF_SUB2, int8_t LUM_INT2, int8_t ANGLE2>
        constexpr auto operator>=(const BaseUnit<U, TIME2, LENGTH2, MASS2, EL_CURR2, TD_TEMP2, AM_OF_SUB2, LUM_INT2, ANGLE2> &other) const -> bool {
            static_assert(same_dim(dim(), std::decay_t<decltype(other)>::dim()), "utl: cannot compare quantities of different dimensions");
            return value_ >= other.value();
        }

    private:
        T value_;
    };

    template<typename T>
    using Unit = BaseUnit<T, 0, 0, 0, 0, 0, 0, 0, 0>;

    template<typename T, typename U1, typename U2>
    using MulBaseUnits = BaseUnit<T,
                                  U1::TimeDim() + U2::TimeDim(),
                                  U1::LengthDim() + U2::LengthDim(),
                                  U1::MassDim() + U2::MassDim(),
                                  U1::ElCurrDim() + U2::ElCurrDim(),
                                  U1::TdTempDim() + U2::TdTempDim(),
                                  U1::AmOfSubDim() + U2::AmOfSubDim(),
                                  U1::LumIntDim() + U2::LumIntDim(),
                                  U1::AngleDim() + U2::AngleDim()>;

    template<typename T, typename U1, typename U2>
    using DivBaseUnits = BaseUnit<T,
                                  U1::TimeDim() - U2::TimeDim(),
                                  U1::LengthDim() - U2::LengthDim(),
                                  U1::MassDim() - U2::MassDim(),
                                  U1::ElCurrDim() - U2::ElCurrDim(),
                                  U1::TdTempDim() - U2::TdTempDim(),
                                  U1::AmOfSubDim() - U2::AmOfSubDim(),
                                  U1::LumIntDim() - U2::LumIntDim(),
                                  U1::AngleDim() - U2::AngleDim()>;

    template<typename T, typename U1>
    using InvBaseUnit = BaseUnit<T,
                                 -U1::TimeDim(),
                                 -U1::LengthDim(),
                                 -U1::MassDim(),
                                 -U1::ElCurrDim(),
                                 -U1::TdTempDim(),
                                 -U1::AmOfSubDim(),
                                 -U1::LumIntDim(),
                                 -U1::AngleDim()>;
} // namespace utl

namespace utl {

    template<typename T>
    using TimeUnit = BaseUnit<T, 1, 0, 0, 0, 0, 0, 0>;

    template<typename T>
    class Time : public TimeUnit<T> {

    public:
        constexpr explicit Time(T time) : TimeUnit<T>{time} {}

        [[nodiscard]] constexpr auto day() const -> T { return static_cast<T>(h() / HOURS_IN_DAY); }

        [[nodiscard]] constexpr auto h() const -> T { return static_cast<T>(s() / SECS_IN_MINUTE / MINUTES_IN_HOUR); }

        [[nodiscard]] constexpr auto min() const -> T { return static_cast<T>(s() / SECS_IN_MINUTE); }

        [[nodiscard]] constexpr auto s() const -> T { return static_cast<T>(this->value()); }

        [[nodiscard]] constexpr auto ms() const -> T { return static_cast<T>(s() / MILLI); }

        [[nodiscard]] constexpr auto us() const -> T { return static_cast<T>(s() / MICRO); }

        [[nodiscard]] constexpr auto ns() const -> T { return static_cast<T>(s() / NANO); }
    };

    template<typename T>
    struct UnitMapper<TimeUnit<T>> {
        using type = Time<T>;
    };
} // namespace utl

namespace utl {

    template<typename T>
    using LengthUnit = BaseUnit<T, 0, 1, 0, 0, 0, 0, 0>;

    template<typename T>
    class Length : public LengthUnit<T> {

        static constexpr double METERS_IN_MILE = 1609.344;
        static constexpr double METERS_IN_YARD = 0.9144;
        static constexpr double METERS_IN_FOOT = 0.3048;
        static constexpr double METERS_IN_INCH = 0.0254;

    public:
        constexpr explicit Length(T length) : LengthUnit<T>{length} {}

        [[nodiscard]] constexpr auto km() const -> T { return static_cast<T>(m() / KILO); }

        [[nodiscard]] constexpr auto m() const -> T { return static_cast<T>(this->value()); }

        [[nodiscard]] constexpr auto mm() const -> T { return static_cast<T>(m() / MILLI); }

        [[nodiscard]] constexpr auto um() const -> T { return static_cast<T>(m() / MICRO); }

        [[nodiscard]] constexpr auto nm() const -> T { return static_cast<T>(m() / NANO); }

        [[nodiscard]] constexpr auto mi() const -> T { return static_cast<T>(m() / METERS_IN_MILE); }

        [[nodiscard]] constexpr auto yd() const -> T { return static_cast<T>(m() / METERS_IN_YARD); }

        [[nodiscard]] constexpr auto ft() const -> T { return static_cast<T>(m() / METERS_IN_FOOT); }

        [[nodiscard]] constexpr auto in() const -> T { return static_cast<T>(m() / METERS_IN_INCH); }
    };

    template<typename T>
    struct UnitMapper<LengthUnit<T>> {
        using type = Length<T>;
    };
} // namespace utl

namespace utl {

    template<typename T>
    using MassUnit = BaseUnit<T, 0, 0, 1, 0, 0, 0, 0>;

    template<typename T>
    class Mass : public MassUnit<T> {

        static constexpr double KILOGRAMS_IN_POUND = 0.45359237;
        static constexpr double KILOGRAMS_IN_OUNCE = 0.028349523125;

    public:
        constexpr explicit Mass(T mass) : MassUnit<T>{mass} {}

        [[nodiscard]] constexpr auto tonne() const -> T { return static_cast<T>(this->value() / KILO); }

        [[nodiscard]] constexpr auto kg() const -> T { return static_cast<T>(this->value()); }

        [[nodiscard]] constexpr auto g() const -> T { return static_cast<T>(this->value() / MILLI); }

        [[nodiscard]] constexpr auto mg() const -> T { return static_cast<T>(this->value() / MICRO); }

        [[nodiscard]] constexpr auto ug() const -> T { return static_cast<T>(this->value() / NANO); }

        [[nodiscard]] constexpr auto lb() const -> T { return static_cast<T>(kg() / KILOGRAMS_IN_POUND); }

        [[nodiscard]] constexpr auto oz() const -> T { return static_cast<T>(kg() / KILOGRAMS_IN_OUNCE); }
    };

    template<typename T>
    struct UnitMapper<MassUnit<T>> {
        using type = Mass<T>;
    };
} // namespace utl

namespace utl {

    template<typename T>
    using ElectricCurrentUnit = BaseUnit<T, 0, 0, 0, 1, 0, 0, 0>;

    template<typename T>
    class ElectricCurrent : public ElectricCurrentUnit<T> {
    public:
        constexpr explicit ElectricCurrent(T current) : ElectricCurrentUnit<T>{current} {}

        [[nodiscard]] constexpr auto kA() const -> T { return static_cast<T>(A() / KILO); }

        [[nodiscard]] constexpr auto A() const -> T { return static_cast<T>(this->value()); }

        [[nodiscard]] constexpr auto mA() const -> T { return static_cast<T>(A() / MILLI); }

        [[nodiscard]] constexpr auto uA() const -> T { return static_cast<T>(A() / MICRO); }

        [[nodiscard]] constexpr auto nA() const -> T { return static_cast<T>(A() / NANO); }
    };

    template<typename T>
    struct UnitMapper<ElectricCurrentUnit<T>> {
        using type = ElectricCurrent<T>;
    };
} // namespace utl

namespace utl {

    static constexpr double TEMPERATURE_K2C = -273.15;
    static constexpr double TEMPERATURE_C2F_K = 1.8;
    static constexpr double TEMPERATURE_C2F_Q = 32;

    template<typename T>
    using TemperatureDeltaUnit = BaseUnit<T, 0, 0, 0, 0, 1, 0, 0>;

    template<typename T>
    class TemperatureDelta : public TemperatureDeltaUnit<T> {

    public:
        constexpr explicit TemperatureDelta(T delta) : TemperatureDeltaUnit<T>{delta} {}

        [[nodiscard]] constexpr auto K() const -> T { return static_cast<T>(this->value()); }

        [[nodiscard]] constexpr auto degC() const -> T { return K(); }

        [[nodiscard]] constexpr auto degF() const -> T { return static_cast<T>(K() * TEMPERATURE_C2F_K); }

        constexpr auto operator+(const TemperatureDelta &other) const -> TemperatureDelta {
            return TemperatureDelta(K() + other.K());
        }

        constexpr auto operator-(const TemperatureDelta &other) const -> TemperatureDelta {
            return TemperatureDelta(K() - other.K());
        }

        constexpr auto operator-() const -> TemperatureDelta {
            return TemperatureDelta(-K());
        }

        constexpr auto operator*(T scalar) const -> TemperatureDelta {
            return TemperatureDelta(K() * scalar);
        }

        constexpr auto operator/(T scalar) const -> TemperatureDelta {
            return TemperatureDelta(K() / scalar);
        }

        friend constexpr auto operator*(T lhs, const TemperatureDelta<T> &rhs) -> TemperatureDelta<T> {
            return TemperatureDelta<T>(rhs.K() * lhs);
        }
    };

    template<typename T>
    using ThermodynamicTemperatureUnit = BaseUnit<T, 0, 0, 0, 0, 1, 0, 0>;

    template<typename T>
    class ThermodynamicTemperature : public ThermodynamicTemperatureUnit<T> {

    public:
        enum class TYPE {
            KELVIN,
            CELSIUS,
            FAHRENHEIT,
        };

    private:
        static constexpr auto to_kelvin(T thermodyn_temp, const TYPE &type) -> T {
            switch (type) {
                case TYPE::CELSIUS:
                    return static_cast<T>(thermodyn_temp - TEMPERATURE_K2C);
                case TYPE::FAHRENHEIT:
                    return static_cast<T>((thermodyn_temp - TEMPERATURE_C2F_Q) / TEMPERATURE_C2F_K);
                default:
                    return thermodyn_temp;
            }
        }

    public:
        constexpr explicit ThermodynamicTemperature(T thermodyn_temp, const TYPE &type = TYPE::KELVIN)
            : ThermodynamicTemperatureUnit<T>{to_kelvin(thermodyn_temp, type)} {}

        [[nodiscard]] constexpr auto K() const -> T { return static_cast<T>(this->value()); }

        [[nodiscard]] constexpr auto degC() const -> T { return static_cast<T>(K() + TEMPERATURE_K2C); }

        [[nodiscard]] constexpr auto degF() const -> T { return static_cast<T>(degC() * TEMPERATURE_C2F_K + TEMPERATURE_C2F_Q); }

        constexpr auto operator-(const ThermodynamicTemperature &other) const -> TemperatureDelta<T> {
            return TemperatureDelta<T>(K() - other.K());
        }

        constexpr auto operator+(const TemperatureDelta<T> &delta) const -> ThermodynamicTemperature {
            return ThermodynamicTemperature(K() + delta.K());
        }

        constexpr auto operator-(const TemperatureDelta<T> &delta) const -> ThermodynamicTemperature {
            return ThermodynamicTemperature(K() - delta.K());
        }

        constexpr auto operator+=(const TemperatureDelta<T> &delta) -> ThermodynamicTemperature & {
            this->set_value(K() + delta.K());
            return *this;
        }

        constexpr auto operator-=(const TemperatureDelta<T> &delta) -> ThermodynamicTemperature & {
            this->set_value(K() - delta.K());
            return *this;
        }

        auto operator+(const ThermodynamicTemperature &other) const -> ThermodynamicTemperature = delete;

        auto operator+=(const ThermodynamicTemperature &other) -> ThermodynamicTemperature & = delete;

        auto operator-=(const ThermodynamicTemperature &other) -> ThermodynamicTemperature & = delete;
    };

    template<typename T>
    constexpr auto operator+(const TemperatureDelta<T> &delta, const ThermodynamicTemperature<T> &temp) -> ThermodynamicTemperature<T> {
        return temp + delta;
    }

    template<typename T>
    struct UnitMapper<ThermodynamicTemperatureUnit<T>> {
        using type = ThermodynamicTemperature<T>;
    };
} // namespace utl

namespace utl {

    template<typename T>
    using AmountOfSubstanceUnit = BaseUnit<T, 0, 0, 0, 0, 0, 1, 0>;

    template<typename T>
    class AmountOfSubstance : public AmountOfSubstanceUnit<T> {
    public:
        constexpr explicit AmountOfSubstance(T amount_of_sub) : AmountOfSubstanceUnit<T>{amount_of_sub} {}

        [[nodiscard]] constexpr auto mol() const -> T { return static_cast<T>(this->value()); }

        [[nodiscard]] constexpr auto mmol() const -> T { return static_cast<T>(mol() / MILLI); }

        [[nodiscard]] constexpr auto umol() const -> T { return static_cast<T>(mol() / MICRO); }

        [[nodiscard]] constexpr auto nmol() const -> T { return static_cast<T>(mol() / NANO); }
    };

    template<typename T>
    struct UnitMapper<AmountOfSubstanceUnit<T>> {
        using type = AmountOfSubstance<T>;
    };
} // namespace utl

namespace utl {

    template<typename T>
    using LuminousIntensityUnit = BaseUnit<T, 0, 0, 0, 0, 0, 0, 1>;

    template<typename T>
    class LuminousIntensity : public LuminousIntensityUnit<T> {
    public:
        constexpr explicit LuminousIntensity(T luminous_intensity) : LuminousIntensityUnit<T>{
                                                                         luminous_intensity} {}

        [[nodiscard]] constexpr auto cd() const -> T { return static_cast<T>(this->value()); }
    };

    template<typename T>
    struct UnitMapper<LuminousIntensityUnit<T>> {
        using type = LuminousIntensity<T>;
    };
} // namespace utl

namespace utl {

    template<typename T>
    using VelocityUnit = BaseUnit<T, -1, 1, 0, 0, 0, 0, 0>;

    template<typename T>
    class Velocity : public VelocityUnit<T> {

        static constexpr double MPS_IN_MPH = 0.44704;

    public:
        constexpr explicit Velocity(T speed) : VelocityUnit<T>{speed} {}

        constexpr explicit Velocity(const Length<T> l, const Time<T> t) : VelocityUnit<T>{l.m() / t.s()} {}

        [[nodiscard]] constexpr auto mps() const -> T { return static_cast<T>(this->value()); }

        [[nodiscard]] constexpr auto mph() const -> T { return static_cast<T>(mps() / MPS_IN_MPH); }

        [[nodiscard]] constexpr auto kmph() const -> T { return static_cast<T>(this->value() * 3.6); }
    };

    template<typename T>
    struct UnitMapper<VelocityUnit<T>> {
        using type = Velocity<T>;
    };
} // namespace utl

namespace utl {

    template<typename T>
    using AccelerationUnit = BaseUnit<T, -2, 1, 0, 0, 0, 0, 0>;

    template<typename T>
    class Acceleration : public AccelerationUnit<T> {

    public:
        constexpr explicit Acceleration(T acc) : AccelerationUnit<T>{acc} {}

        constexpr explicit Acceleration(const Velocity<T> v, const Time<T> t) : AccelerationUnit<T>{v.mps() / t.s()} {}

        [[nodiscard]] constexpr auto mps2() const -> T { return static_cast<T>(this->value()); }
    };

    template<typename T>
    struct UnitMapper<AccelerationUnit<T>> {
        using type = Acceleration<T>;
    };
} // namespace utl

namespace utl {

    template<typename T>
    using ForceUnit = BaseUnit<T, -2, 1, 1, 0, 0, 0, 0>;

    template<typename T>
    class Force : public ForceUnit<T> {

    public:
        constexpr explicit Force(T force) : ForceUnit<T>{force} {}

        constexpr explicit Force(const Mass<T> &m, const Acceleration<T> &acc) : ForceUnit<T>{m.kg() * acc.mps2()} {}

        [[nodiscard]] constexpr auto kN() const -> T { return static_cast<T>(N() / KILO); }

        [[nodiscard]] constexpr auto N() const -> T { return static_cast<T>(this->value()); }
    };

    template<typename T>
    struct UnitMapper<ForceUnit<T>> {
        using type = Force<T>;
    };
} // namespace utl

namespace utl {

    template<typename T>
    using EnergyUnit = BaseUnit<T, -2, 2, 1, 0, 0, 0, 0>;

    template<typename T>
    class Energy : public EnergyUnit<T> {

        static constexpr double JOULES_IN_KILOWATHOUR = 3600000.0;
        static constexpr double EVS_IN_JOULE = 6.241509e18;
        static constexpr double JOULES_IN_WATTHOUR = 3600.0;
        static constexpr double JOULES_IN_CALORIE = 4.184;

    public:
        constexpr explicit Energy(T energy) : EnergyUnit<T>{energy} {}

        constexpr explicit Energy(const Force<T> &f, const Length<T> &l) : EnergyUnit<T>{f.N() * l.m()} {}

        [[nodiscard]] constexpr auto kJ() const -> T { return static_cast<T>(J() / KILO); }

        [[nodiscard]] constexpr auto J() const -> T { return static_cast<T>(this->value()); }

        [[nodiscard]] constexpr auto mJ() const -> T { return static_cast<T>(J() / MILLI); }

        [[nodiscard]] constexpr auto kWh() const -> T { return static_cast<T>(J() / JOULES_IN_KILOWATHOUR); }

        [[nodiscard]] constexpr auto eV() const -> T { return static_cast<T>(J() * EVS_IN_JOULE); }

        [[nodiscard]] constexpr auto Wh() const -> T { return static_cast<T>(J() / JOULES_IN_WATTHOUR); }

        [[nodiscard]] constexpr auto cal() const -> T { return static_cast<T>(J() / JOULES_IN_CALORIE); }
    };

    template<typename T>
    struct UnitMapper<EnergyUnit<T>> {
        using type = Energy<T>;
    };
} // namespace utl

namespace utl {

    template<typename T>
    using AbsorbedDoseUnit = BaseUnit<T, -2, 2, 0, 0, 0, 0, 0>;

    template<typename T>
    class AbsorbedDose : public AbsorbedDoseUnit<T> {

    public:
        constexpr explicit AbsorbedDose(T abs_dose) : AbsorbedDoseUnit<T>{abs_dose} {}

        constexpr explicit AbsorbedDose(const Energy<T> &e, const Mass<T> &m) : AbsorbedDoseUnit<T>{e.J() / m.kg()} {}

        [[nodiscard]] constexpr auto Gy() const -> T { return static_cast<T>(this->value()); }
    };

    template<typename T>
    struct UnitMapper<AbsorbedDoseUnit<T>> {
        using type = AbsorbedDose<T>;
    };
} // namespace utl

namespace utl {

    template<typename T>
    using ActivityUnit = BaseUnit<T, -1, 0, 0, 0, 0, 0, 0>;

    template<typename T>
    class Activity : public ActivityUnit<T> {

    public:
        constexpr explicit Activity(T activity) : ActivityUnit<T>{activity} {}

        [[nodiscard]] constexpr auto Bq() const -> T { return static_cast<T>(this->value()); }

        constexpr auto operator+(const Activity &other) const -> Activity {
            return Activity(Bq() + other.Bq());
        }

        constexpr auto operator-(const Activity &other) const -> Activity {
            return Activity(Bq() - other.Bq());
        }

        constexpr auto operator-() const -> Activity {
            return Activity(-Bq());
        }

        constexpr auto operator*(T scalar) const -> Activity {
            return Activity(Bq() * scalar);
        }

        constexpr auto operator/(T scalar) const -> Activity {
            return Activity(Bq() / scalar);
        }

        friend constexpr auto operator*(T lhs, const Activity<T> &rhs) -> Activity<T> {
            return Activity<T>(rhs.Bq() * lhs);
        }
    };

    //    template<typename T>
    //    struct UnitMapper<ActivityUnit<T>> {
    //        using type = Activity<T>;
    //    };
} // namespace utl

namespace utl {

    template<typename T>
    using ElectricChargeUnit = BaseUnit<T, 1, 0, 0, 1, 0, 0, 0>;

    template<typename T>
    class ElectricCharge : public ElectricChargeUnit<T> {
    public:
        constexpr explicit ElectricCharge(const T &charge) : ElectricChargeUnit<T>{charge} {}

        constexpr explicit ElectricCharge(const ElectricCurrent<T> &ec, const Time<T> &t) : ElectricChargeUnit<T>{
                                                                                                ec.A() * t.s()} {}

        [[nodiscard]] constexpr auto C() const -> T { return static_cast<T>(this->value()); }
    };

    template<typename T>
    struct UnitMapper<ElectricChargeUnit<T>> {
        using type = ElectricCharge<T>;
    };
} // namespace utl

namespace utl {

    template<typename T>
    using FrequencyUnit = BaseUnit<T, -1, 0, 0, 0, 0, 0, 0>;

    template<typename T>
    class Frequency : public FrequencyUnit<T> {

    public:
        constexpr explicit Frequency(T freq) : FrequencyUnit<T>{freq} {}

        [[nodiscard]] constexpr auto THz() const -> T { return static_cast<T>(Hz() / TERA); }

        [[nodiscard]] constexpr auto GHz() const -> T { return static_cast<T>(Hz() / GIGA); }

        [[nodiscard]] constexpr auto MHz() const -> T { return static_cast<T>(Hz() / MEGA); }

        [[nodiscard]] constexpr auto kHz() const -> T { return static_cast<T>(Hz() / KILO); }

        [[nodiscard]] constexpr auto Hz() const -> T { return static_cast<T>(this->value()); }
    };

    template<typename T>
    struct UnitMapper<FrequencyUnit<T>> {
        using type = Frequency<T>;
    };
} // namespace utl

namespace utl {

    template<typename T>
    using PowerUnit = BaseUnit<T, -3, 2, 1, 0, 0, 0, 0>;

    template<typename T>
    class Power : public PowerUnit<T> {

        static constexpr double WATTS_IN_HORSEPOWER = 745.6998715822702;

    public:
        constexpr explicit Power(T power) : PowerUnit<T>{power} {}

        constexpr explicit Power(const Energy<T> &e, const Time<T> &t) : PowerUnit<T>{e.J() / t.s()} {}

        [[nodiscard]] constexpr auto kW() const -> T { return static_cast<T>(W() / KILO); }

        [[nodiscard]] constexpr auto W() const -> T { return static_cast<T>(this->value()); }

        [[nodiscard]] constexpr auto hp() const -> T { return static_cast<T>(W() / WATTS_IN_HORSEPOWER); }
    };

    template<typename T>
    struct UnitMapper<PowerUnit<T>> {
        using type = Power<T>;
    };
} // namespace utl

namespace utl {

    template<typename T>
    using VoltageUnit = BaseUnit<T, -3, 2, 1, -1, 0, 0, 0>;

    template<typename T>
    class Voltage : public VoltageUnit<T> {
    public:
        constexpr explicit Voltage(T voltage) : VoltageUnit<T>{voltage} {}

        constexpr explicit Voltage(const Power<T> &p, const ElectricCurrent<T> &ec = 1) : VoltageUnit<T>{p.W() / ec.A()} {}

        [[nodiscard]] constexpr auto V() const -> T { return static_cast<T>(this->value()); }

        [[nodiscard]] constexpr auto kV() const -> T { return static_cast<T>(V() / KILO); }

        [[nodiscard]] constexpr auto mV() const -> T { return static_cast<T>(V() / MILLI); }
    };

    template<typename T>
    struct UnitMapper<VoltageUnit<T>> {
        using type = Voltage<T>;
    };
} // namespace utl

namespace utl {

    template<typename T>
    using CapacitanceUnit = BaseUnit<T, 4, -2, -1, 2, 0, 0, 0>;

    template<typename T>
    class Capacitance : public CapacitanceUnit<T> {
    public:
        constexpr explicit Capacitance(T cap) : CapacitanceUnit<T>{cap} {}

        [[nodiscard]] constexpr auto F() const -> T { return static_cast<T>(this->value()); }

        [[nodiscard]] constexpr auto mF() const -> T { return static_cast<T>(F() / MILLI); }

        [[nodiscard]] constexpr auto uF() const -> T { return static_cast<T>(F() / MICRO); }

        [[nodiscard]] constexpr auto nF() const -> T { return static_cast<T>(F() / NANO); }

        [[nodiscard]] constexpr auto pF() const -> T { return static_cast<T>(F() / PICO); }
    };

    template<typename T>
    struct UnitMapper<CapacitanceUnit<T>> {
        using type = Capacitance<T>;
    };
} // namespace utl

namespace utl {

    template<typename T>
    using CatalyticActivityUnit = BaseUnit<T, -1, 0, 0, 0, 0, 1, 0>;

    template<typename T>
    class CatalyticActivity : public BaseUnit<T, -1, 0, 0, 0, 0, 1, 0> {
    public:
        constexpr explicit CatalyticActivity(T catalytic_activity) : CatalyticActivityUnit<T>{catalytic_activity} {}

        constexpr explicit CatalyticActivity(const AmountOfSubstance<T> &aos, const Time<T> &t) : CatalyticActivityUnit<T>{
                                                                                                      aos.mol() / t.s()} {}

        [[nodiscard]] constexpr auto katal() const -> T { return static_cast<T>(this->value()); }
    };

    template<typename T>
    struct UnitMapper<CatalyticActivityUnit<T>> {
        using type = CatalyticActivity<T>;
    };
} // namespace utl

namespace utl {

    template<typename T>
    using ResistanceUnit = BaseUnit<T, -3, 2, 1, -2, 0, 0, 0>;

    template<typename T>
    class Resistance : public ResistanceUnit<T> {
    public:
        constexpr explicit Resistance(T res) : ResistanceUnit<T>{res} {}

        constexpr explicit Resistance(const Voltage<T> &v, const ElectricCurrent<T> &ec) : ResistanceUnit<T>{v.V() / ec.A()} {}

        [[nodiscard]] constexpr auto MOhm() const -> T { return static_cast<T>(this->value() / MEGA); }

        [[nodiscard]] constexpr auto kOhm() const -> T { return static_cast<T>(this->value() / KILO); }

        [[nodiscard]] constexpr auto Ohm() const -> T { return static_cast<T>(this->value()); }

        [[nodiscard]] constexpr auto mOhm() const -> T { return static_cast<T>(this->value() / MILLI); }
    };

    template<typename T>
    struct UnitMapper<ResistanceUnit<T>> {
        using type = Resistance<T>;
    };
} // namespace utl

namespace utl {

    template<typename T>
    using ConductanceUnit = BaseUnit<T, 3, -2, -1, 2, 0, 0, 0>;

    template<typename T>
    class Conductance : public ConductanceUnit<T> {
    public:
        constexpr explicit Conductance(T cap) : ConductanceUnit<T>{cap} {}

        constexpr explicit Conductance(const ElectricCurrent<T> &ec, const Voltage<T> &v) : ConductanceUnit<T>{ec.A() / v.V()} {}

        [[nodiscard]] constexpr auto S() const -> T { return static_cast<T>(this->value()); }
    };

    template<typename T>
    struct UnitMapper<ConductanceUnit<T>> {
        using type = Conductance<T>;
    };
} // namespace utl

namespace utl {

    template<typename T>
    using DoseEquivalentUnit = BaseUnit<T, -2, 2, 0, 0, 0, 0, 0>;

    template<typename T>
    class DoseEquivalent : public DoseEquivalentUnit<T> {

    public:
        constexpr explicit DoseEquivalent(T dose_eq) : DoseEquivalentUnit<T>{dose_eq} {}

        constexpr explicit DoseEquivalent(const AbsorbedDose<T> ad, const T radiation_weight_factor) : DoseEquivalentUnit<T>{ad.Gy() * radiation_weight_factor} {}

        [[nodiscard]] constexpr auto Sv() const -> T { return static_cast<T>(this->value()); }

        constexpr auto operator+(const DoseEquivalent &other) const -> DoseEquivalent {
            return DoseEquivalent(Sv() + other.Sv());
        }

        constexpr auto operator-(const DoseEquivalent &other) const -> DoseEquivalent {
            return DoseEquivalent(Sv() - other.Sv());
        }

        constexpr auto operator-() const -> DoseEquivalent {
            return DoseEquivalent(-Sv());
        }

        constexpr auto operator*(T scalar) const -> DoseEquivalent {
            return DoseEquivalent(Sv() * scalar);
        }

        constexpr auto operator/(T scalar) const -> DoseEquivalent {
            return DoseEquivalent(Sv() / scalar);
        }

        friend constexpr auto operator*(T lhs, const DoseEquivalent<T> &rhs) -> DoseEquivalent<T> {
            return DoseEquivalent<T>(rhs.Sv() * lhs);
        }
    };
} // namespace utl

namespace utl {

    template<typename T>
    using AreaUnit = BaseUnit<T, 0, 2, 0, 0, 0, 0, 0>;

    template<typename T>
    class Area : public AreaUnit<T> {

    public:
        constexpr explicit Area(T area) : AreaUnit<T>{area} {}

        constexpr explicit Area(const Length<T> l1, const Length<T> l2) : AreaUnit<T>{l1.m() * l2.m()} {}

        [[nodiscard]] constexpr auto km2() const -> T { return static_cast<T>(m2() / KILO / KILO); }

        [[nodiscard]] constexpr auto ha() const -> T { return static_cast<T>(a() / HECTO); }

        [[nodiscard]] constexpr auto a() const -> T { return static_cast<T>(m2() / HECTO); }

        [[nodiscard]] constexpr auto m2() const -> T { return static_cast<T>(this->value()); }

        [[nodiscard]] constexpr auto mm2() const -> T { return static_cast<T>(m2() / MILLI / MILLI); }

        [[nodiscard]] constexpr auto um2() const -> T { return static_cast<T>(m2() / MICRO / MICRO); }

        [[nodiscard]] constexpr auto nm2() const -> T { return static_cast<T>(m2() / NANO / NANO); }
    };

    template<typename T>
    struct UnitMapper<AreaUnit<T>> {
        using type = Area<T>;
    };
} // namespace utl

namespace utl {

    template<typename T>
    using SolidAngleUnit = BaseUnit<T, 0, 0, 0, 0, 0, 0, 0, 2>;

    template<typename T>
    class SolidAngle : public SolidAngleUnit<T> {
    public:
        constexpr explicit SolidAngle(T solid_angle) : SolidAngleUnit<T>{solid_angle} {}

        constexpr explicit SolidAngle(Area<T> a1, Area<T> a2) : SolidAngleUnit<T>{a1.m2() / a2.m2()} {};

        constexpr explicit SolidAngle(Area<T> a, Length<T> r) : SolidAngleUnit<T>{a.m2() / r.m() / r.m()} {};

        [[nodiscard]] constexpr auto sr() const -> T { return static_cast<T>(this->value()); }
    };

    template<typename T>
    struct UnitMapper<SolidAngleUnit<T>> {
        using type = SolidAngle<T>;
    };
} // namespace utl

namespace utl {

    template<typename T>
    using LuminousFluxUnit = BaseUnit<T, 0, 0, 0, 0, 0, 0, 1, 2>;

    template<typename T>
    class LuminousFlux : public LuminousFluxUnit<T> {
    public:
        constexpr explicit LuminousFlux(T luminous_flux) : LuminousFluxUnit<T>{
                                                               luminous_flux} {}

        constexpr explicit LuminousFlux(const LuminousIntensity<T> &lum_int, const SolidAngle<T> &solid_angle)
            : LuminousFluxUnit<T>{
                  lum_int.cd() * solid_angle.sr()} {}

        [[nodiscard]] constexpr auto lm() const -> T { return static_cast<T>(this->value()); }
    };

    template<typename T>
    struct UnitMapper<LuminousFluxUnit<T>> {
        using type = LuminousFlux<T>;
    };

} // namespace utl

namespace utl {

    template<typename T>
    using IlluminanceUnit = BaseUnit<T, 0, -2, 0, 0, 0, 0, 1, 2>;

    template<typename T>
    class Illuminance : public IlluminanceUnit<T> {
    public:
        constexpr explicit Illuminance(T illuminance) : IlluminanceUnit<T>{
                                                            illuminance} {}

        constexpr explicit Illuminance(const LuminousFlux<T> &lf, const Area<T> &a) : IlluminanceUnit<T>{
                                                                                          lf.lm() / a.m2()} {}

        [[nodiscard]] constexpr auto lux() const -> T { return static_cast<T>(this->value()); }
    };

    template<typename T>
    struct UnitMapper<IlluminanceUnit<T>> {
        using type = Illuminance<T>;
    };
} // namespace utl

namespace utl {

    template<typename T>
    class MagneticFluxDensity;

    template<typename T>
    using MagneticFluxUnit = BaseUnit<T, -2, 2, 1, -1, 0, 0, 0>;

    template<typename T>
    class MagneticFlux : public MagneticFluxUnit<T> {
    public:
        constexpr explicit MagneticFlux(T illuminance) : MagneticFluxUnit<T>{illuminance} {}

        constexpr explicit MagneticFlux(const Voltage<T> &v, const Time<T> &t) : MagneticFluxUnit<T>{
                                                                                     v.V() * t.s()} {}

        constexpr explicit MagneticFlux(const MagneticFluxDensity<T> &mfd, const Area<T> &a) : MagneticFluxUnit<T>{
                                                                                                   mfd.Tesla() * a.m2()} {}

        [[nodiscard]] constexpr auto Wb() const -> T { return static_cast<T>(this->value()); }
    };

    template<typename T>
    struct UnitMapper<MagneticFluxUnit<T>> {
        using type = MagneticFlux<T>;
    };
} // namespace utl

namespace utl {

    template<typename T>
    using InductanceUnit = BaseUnit<T, -2, 2, 1, -2, 0, 0, 0>;

    template<typename T>
    class Inductance : public InductanceUnit<T> {
    public:
        constexpr explicit Inductance(T illuminance) : InductanceUnit<T>{illuminance} {}

        constexpr explicit Inductance(const MagneticFlux<T> &mf, const ElectricCurrent<T> &ec) : InductanceUnit<T>{
                                                                                                     mf.Wb() / ec.A()} {}

        [[nodiscard]] constexpr auto H() const -> T { return static_cast<T>(this->value()); }
    };

    template<typename T>
    struct UnitMapper<InductanceUnit<T>> {
        using type = Inductance<T>;
    };
} // namespace utl

namespace utl {

    template<typename T>
    class MagneticFluxDensity;

    template<typename T>
    using MagneticFluxDensityUnit = BaseUnit<T, -2, 0, 1, -1, 0, 0, 0>;

    template<typename T>
    class MagneticFluxDensity : public MagneticFluxDensityUnit<T> {
    public:
        constexpr explicit MagneticFluxDensity(T illuminance) : MagneticFluxDensityUnit<T>{illuminance} {}

        constexpr explicit MagneticFluxDensity(const MagneticFlux<T> &mf, const Area<T> &a) : MagneticFluxDensityUnit<T>{
                                                                                                  mf.Wb() / a.m2()} {}

        [[nodiscard]] constexpr auto Tesla() const -> T { return static_cast<T>(this->value()); }
    };

    template<typename T>
    struct UnitMapper<MagneticFluxDensityUnit<T>> {
        using type = MagneticFluxDensity<T>;
    };
} // namespace utl

namespace utl {

    template<typename T>
    using PressureUnit = BaseUnit<T, -2, -1, 1, 0, 0, 0, 0>;

    template<typename T>
    class Pressure : public PressureUnit<T> {

        static constexpr double PASCALS_IN_BAR = 1e5;
        static constexpr double PASCALS_IN_ATMOSPHERE = 101325.0;
        static constexpr double PASCALS_IN_PSI = 6894.757293168361;

    public:
        constexpr explicit Pressure(T pressure) : PressureUnit<T>{pressure} {}

        constexpr explicit Pressure(const Force<T> &f, const Area<T> &a) : PressureUnit<T>{f.N() / a.m2()} {}

        [[nodiscard]] constexpr auto kPa() const -> T { return static_cast<T>(Pa() / KILO); }

        [[nodiscard]] constexpr auto hPa() const -> T { return static_cast<T>(Pa() / HECTO); }

        [[nodiscard]] constexpr auto Pa() const -> T { return static_cast<T>(this->value()); }

        [[nodiscard]] constexpr auto bar() const -> T { return static_cast<T>(Pa() / PASCALS_IN_BAR); }

        [[nodiscard]] constexpr auto atm() const -> T { return static_cast<T>(Pa() / PASCALS_IN_ATMOSPHERE); }

        [[nodiscard]] constexpr auto psi() const -> T { return static_cast<T>(Pa() / PASCALS_IN_PSI); }
    };

    template<typename T>
    struct UnitMapper<PressureUnit<T>> {
        using type = Pressure<T>;
    };
} // namespace utl

namespace utl {

    template<typename T>
    using TorqueUnit = BaseUnit<T, -2, 2, 1, 0, 0, 0, 0, -1>;

    template<typename T>
    class Torque : public TorqueUnit<T> {
    public:
        constexpr explicit Torque(T torque) : TorqueUnit<T>{torque} {}

        [[nodiscard]] constexpr auto Nm() const -> T { return static_cast<T>(this->value()); }
    };

    template<typename T>
    struct UnitMapper<TorqueUnit<T>> {
        using type = Torque<T>;
    };
} // namespace utl

namespace utl {

    template<typename T>
    using AngleUnit = BaseUnit<T, 0, 0, 0, 0, 0, 0, 0, 1>;

    template<typename T>
    class Angle : public AngleUnit<T> {
    public:
        enum class TYPE {
            RAD,
            DEG,
        };

    private:
        static constexpr auto to_rad(T angle, const TYPE &type) -> T {
            switch (type) {
                case TYPE::DEG:
                    return static_cast<T>(angle / 180 * PI);
                default:
                    return angle;
            }
        }

    public:
        constexpr explicit Angle(T angle, const TYPE &type = TYPE::RAD)
            : AngleUnit<T>{to_rad(angle, type)} {}

        constexpr explicit Angle(Length<T> s, Length<T> r) : AngleUnit<T>{s.m() / r.m()} {};

        [[nodiscard]] constexpr auto rad() const -> T { return static_cast<T>(this->value()); }

        [[nodiscard]] constexpr auto deg() const -> T { return static_cast<T>(rad() / PI * 180.0); }
    };

    template<typename T>
    struct UnitMapper<AngleUnit<T>> {
        using type = Angle<T>;
    };

    template<typename T>
    auto sin(const Angle<T> &angle) -> T { return static_cast<T>(std::sin(angle.rad())); }

    template<typename T>
    auto cos(const Angle<T> &angle) -> T { return static_cast<T>(std::cos(angle.rad())); }

    template<typename T>
    auto tan(const Angle<T> &angle) -> T { return static_cast<T>(std::tan(angle.rad())); }

} // namespace utl

// coherent derived units in terms of base units

namespace utl {
    template<typename T>
    using VolumeUnit = BaseUnit<T, 0, 3, 0, 0, 0, 0, 0>;

    template<typename T>
    class Volume : public VolumeUnit<T> {

        static constexpr double LITERS_IN_M3 = 1000;

    public:
        constexpr explicit Volume(T volume) : VolumeUnit<T>{volume} {}

        constexpr explicit Volume(const Length<T> l1, const Length<T> l2, const Length<T> l3) : VolumeUnit<T>{
                                                                                                    l1.m() * l2.m() * l3.m()} {}

        constexpr explicit Volume(const Area<T> a, const Length<T> l) : VolumeUnit<T>{a.m2() * l.m()} {}

        [[nodiscard]] constexpr auto m3() const -> T { return static_cast<T>(this->value()); }

        [[nodiscard]] constexpr auto l() const -> T { return static_cast<T>(this->value() * LITERS_IN_M3); }
    };

    template<typename T>
    struct UnitMapper<VolumeUnit<T>> {
        using type = Volume<T>;
    };
} // namespace utl

namespace utl {

    template<typename T>
    using VergenceUnit = BaseUnit<T, 0, -1, 0, 0, 0, 0, 0>;

    template<typename T>
    class Vergence : public VergenceUnit<T> {

    public:
        constexpr explicit Vergence(T vergence) : VergenceUnit<T>{vergence} {}

        constexpr explicit Vergence(const Length<T> focal_length) : VergenceUnit<T>{static_cast<T>(1.0) / focal_length.m()} {}

        [[nodiscard]] constexpr auto dpt() const -> T { return static_cast<T>(this->value()); }
    };

    template<typename T>
    struct UnitMapper<VergenceUnit<T>> {
        using type = Vergence<T>;
    };
} // namespace utl

namespace utl {

    template<typename T>
    using DensityUnit = BaseUnit<T, 0, -3, 1, 0, 0, 0, 0>;

    template<typename T>
    class Density : public DensityUnit<T> {

    public:
        constexpr explicit Density(T density) : DensityUnit<T>{density} {}

        constexpr explicit Density(const Mass<T> &m, const Volume<T> &v) : DensityUnit<T>{m.kg() / v.m3()} {}

        [[nodiscard]] constexpr auto kgpm3() const -> T { return static_cast<T>(this->value()); }
    };

    template<typename T>
    struct UnitMapper<DensityUnit<T>> {
        using type = Density<T>;
    };
} // namespace utl

namespace utl {

    template<typename T>
    using CurrentDensityUnit = BaseUnit<T, 0, -2, 0, 1, 0, 0, 0>;

    template<typename T>
    class CurrentDensity : public CurrentDensityUnit<T> {

    public:
        constexpr explicit CurrentDensity(T current_density) : CurrentDensityUnit<T>{current_density} {}

        constexpr explicit CurrentDensity(const ElectricCurrent<T> &i, const Area<T> &a) : CurrentDensityUnit<T>{i.A() / a.m2()} {}

        [[nodiscard]] constexpr auto Apm2() const -> T { return static_cast<T>(this->value()); }
    };

    template<typename T>
    struct UnitMapper<CurrentDensityUnit<T>> {
        using type = CurrentDensity<T>;
    };
} // namespace utl

namespace utl {

    template<typename T>
    using ConcentrationUnit = BaseUnit<T, 0, -3, 0, 0, 0, 1, 0>;

    template<typename T>
    class Concentration : public ConcentrationUnit<T> {

    public:
        constexpr explicit Concentration(T concentration) : ConcentrationUnit<T>{concentration} {}

        constexpr explicit Concentration(const AmountOfSubstance<T> &n, const Volume<T> &v) : ConcentrationUnit<T>{n.mol() / v.m3()} {}

        [[nodiscard]] constexpr auto molpm3() const -> T { return static_cast<T>(this->value()); }
    };

    template<typename T>
    struct UnitMapper<ConcentrationUnit<T>> {
        using type = Concentration<T>;
    };
} // namespace utl

namespace utl {

    template<typename T>
    using LuminanceUnit = BaseUnit<T, 0, -2, 0, 0, 0, 0, 1>;

    template<typename T>
    class Luminance : public LuminanceUnit<T> {

    public:
        constexpr explicit Luminance(T luminance) : LuminanceUnit<T>{luminance} {}

        constexpr explicit Luminance(const LuminousIntensity<T> &i, const Area<T> &a) : LuminanceUnit<T>{i.cd() / a.m2()} {}

        [[nodiscard]] constexpr auto cdpm2() const -> T { return static_cast<T>(this->value()); }
    };

    template<typename T>
    struct UnitMapper<LuminanceUnit<T>> {
        using type = Luminance<T>;
    };
} // namespace utl

// TODO:
// #include "surface_density.hpp"  // kg/m^2
// #include "specific_volume.hpp"  // m^3/kg
// #include "magnetic_filed_strength.hpp"  // A/m
// #include "mass_concentration.hpp"  // kg/m^3

namespace utl {
    constexpr double CAESIUM_HYPERFINE_FREQ_VALUE = 9192631770;  // Hz
    constexpr double SPEED_OF_LIGHT_IN_VACUUM_VALUE = 299792458; // m/s
    constexpr double PLANCK_CONSTANT_VALUE = 6.62607015e-34;     // J*s
    constexpr double ELEMENTARY_CHARGE_VALUE = 1.602176634e-19;  // C
    constexpr double BOLTZMANN_CONSTANT_VALUE = 1.380649e-23;    // J/K
    constexpr double AVOGADRO_CONSTANT_VALUE = 6.02214076e23;    // mol^-1
    constexpr double LUMINOUS_EFFICACY_VALUE = 683;              // lm/W
} // namespace utl

namespace utl {

    template<typename T_L, typename T_R,
             int8_t TIME_L, int8_t LENGTH_L, int8_t MASS_L, int8_t EL_CURR_L, int8_t TD_TEMP_L, int8_t AM_OF_SUB_L, int8_t LUM_INT_L, int8_t ANGLE_L,
             int8_t TIME_R, int8_t LENGTH_R, int8_t MASS_R, int8_t EL_CURR_R, int8_t TD_TEMP_R, int8_t AM_OF_SUB_R, int8_t LUM_INT_R, int8_t ANGLE_R>
    constexpr auto operator*(
        const BaseUnit<T_L, TIME_L, LENGTH_L, MASS_L, EL_CURR_L, TD_TEMP_L, AM_OF_SUB_L, LUM_INT_L, ANGLE_L> &lhs,
        const BaseUnit<T_R, TIME_R, LENGTH_R, MASS_R, EL_CURR_R, TD_TEMP_R, AM_OF_SUB_R, LUM_INT_R, ANGLE_R> &rhs)
        -> mapped_unit_t<BaseUnit<std::common_type_t<T_L, T_R>,
                                  TIME_L + TIME_R,
                                  LENGTH_L + LENGTH_R,
                                  MASS_L + MASS_R,
                                  EL_CURR_L + EL_CURR_R,
                                  TD_TEMP_L + TD_TEMP_R,
                                  AM_OF_SUB_L + AM_OF_SUB_R,
                                  LUM_INT_L + LUM_INT_R,
                                  ANGLE_L + ANGLE_R>> {
        using Result = mapped_unit_t<BaseUnit<std::common_type_t<T_L, T_R>,
                                              TIME_L + TIME_R,
                                              LENGTH_L + LENGTH_R,
                                              MASS_L + MASS_R,
                                              EL_CURR_L + EL_CURR_R,
                                              TD_TEMP_L + TD_TEMP_R,
                                              AM_OF_SUB_L + AM_OF_SUB_R,
                                              LUM_INT_L + LUM_INT_R,
                                              ANGLE_L + ANGLE_R>>;
        return Result(lhs.value() * rhs.value());
    }

    template<typename T_L, typename T_R,
             int8_t TIME_L, int8_t LENGTH_L, int8_t MASS_L, int8_t EL_CURR_L, int8_t TD_TEMP_L, int8_t AM_OF_SUB_L, int8_t LUM_INT_L, int8_t ANGLE_L,
             int8_t TIME_R, int8_t LENGTH_R, int8_t MASS_R, int8_t EL_CURR_R, int8_t TD_TEMP_R, int8_t AM_OF_SUB_R, int8_t LUM_INT_R, int8_t ANGLE_R>
    constexpr auto operator/(
        const BaseUnit<T_L, TIME_L, LENGTH_L, MASS_L, EL_CURR_L, TD_TEMP_L, AM_OF_SUB_L, LUM_INT_L, ANGLE_L> &lhs,
        const BaseUnit<T_R, TIME_R, LENGTH_R, MASS_R, EL_CURR_R, TD_TEMP_R, AM_OF_SUB_R, LUM_INT_R, ANGLE_R> &rhs)
        -> mapped_unit_t<BaseUnit<std::common_type_t<T_L, T_R>,
                                  TIME_L - TIME_R,
                                  LENGTH_L - LENGTH_R,
                                  MASS_L - MASS_R,
                                  EL_CURR_L - EL_CURR_R,
                                  TD_TEMP_L - TD_TEMP_R,
                                  AM_OF_SUB_L - AM_OF_SUB_R,
                                  LUM_INT_L - LUM_INT_R,
                                  ANGLE_L - ANGLE_R>> {
        using Result = mapped_unit_t<BaseUnit<std::common_type_t<T_L, T_R>,
                                              TIME_L - TIME_R,
                                              LENGTH_L - LENGTH_R,
                                              MASS_L - MASS_R,
                                              EL_CURR_L - EL_CURR_R,
                                              TD_TEMP_L - TD_TEMP_R,
                                              AM_OF_SUB_L - AM_OF_SUB_R,
                                              LUM_INT_L - LUM_INT_R,
                                              ANGLE_L - ANGLE_R>>;
        return Result(lhs.value() / rhs.value());
    }
} // namespace utl

#define UTL_DEFINE_LITERAL(suffix, UnitType, FACTOR)                               \
    constexpr auto operator"" suffix(long double value)->UnitType<double> {        \
        return UnitType<double>(static_cast<double>(value) * (FACTOR));            \
    }                                                                              \
    constexpr auto operator"" suffix(unsigned long long value)->UnitType<double> { \
        return UnitType<double>(static_cast<double>(value) * (FACTOR));            \
    }

namespace utl {
    namespace literals {

        UTL_DEFINE_LITERAL(_h, Time, SECS_IN_MINUTE *MINUTES_IN_HOUR)
        UTL_DEFINE_LITERAL(_min, Time, SECS_IN_MINUTE)
        UTL_DEFINE_LITERAL(_s, Time, 1.0)
        UTL_DEFINE_LITERAL(_ms, Time, MILLI)

        UTL_DEFINE_LITERAL(_km, Length, KILO)
        UTL_DEFINE_LITERAL(_m, Length, 1.0)
        UTL_DEFINE_LITERAL(_mm, Length, MILLI)

        UTL_DEFINE_LITERAL(_kg, Mass, 1.0)
        UTL_DEFINE_LITERAL(_g, Mass, MILLI)

        UTL_DEFINE_LITERAL(_A, ElectricCurrent, 1.0)
        UTL_DEFINE_LITERAL(_K, ThermodynamicTemperature, 1.0)
        UTL_DEFINE_LITERAL(_mol, AmountOfSubstance, 1.0)
        UTL_DEFINE_LITERAL(_cd, LuminousIntensity, 1.0)

        UTL_DEFINE_LITERAL(_mps, Velocity, 1.0)
        UTL_DEFINE_LITERAL(_kmph, Velocity, 1.0 / 3.6)

        UTL_DEFINE_LITERAL(_N, Force, 1.0)
        UTL_DEFINE_LITERAL(_J, Energy, 1.0)
        UTL_DEFINE_LITERAL(_W, Power, 1.0)
        UTL_DEFINE_LITERAL(_Hz, Frequency, 1.0)
        UTL_DEFINE_LITERAL(_Pa, Pressure, 1.0)
        UTL_DEFINE_LITERAL(_V, Voltage, 1.0)
        UTL_DEFINE_LITERAL(_rad, Angle, 1.0)
    } // namespace literals
} // namespace utl

#undef UTL_DEFINE_LITERAL

namespace utl {

    template<typename T, int8_t TIME, int8_t LENGTH, int8_t MASS, int8_t EL_CURR, int8_t TD_TEMP, int8_t AM_OF_SUB, int8_t LUM_INT, int8_t ANGLE>
    auto sqrt(const BaseUnit<T, TIME, LENGTH, MASS, EL_CURR, TD_TEMP, AM_OF_SUB, LUM_INT, ANGLE> &unit)
        -> mapped_unit_t<BaseUnit<T, TIME / 2, LENGTH / 2, MASS / 2, EL_CURR / 2, TD_TEMP / 2, AM_OF_SUB / 2, LUM_INT / 2, ANGLE / 2>> {
        static_assert(TIME % 2 == 0 && LENGTH % 2 == 0 && MASS % 2 == 0 && EL_CURR % 2 == 0 && TD_TEMP % 2 == 0 && AM_OF_SUB % 2 == 0 && LUM_INT % 2 == 0 && ANGLE % 2 == 0,
                      "sqrt requires all dimension exponents to be even");
        using Result = mapped_unit_t<BaseUnit<T, TIME / 2, LENGTH / 2, MASS / 2, EL_CURR / 2, TD_TEMP / 2, AM_OF_SUB / 2, LUM_INT / 2, ANGLE / 2>>;
        return Result(std::sqrt(unit.value()));
    }

    template<int8_t N, typename T, int8_t TIME, int8_t LENGTH, int8_t MASS, int8_t EL_CURR, int8_t TD_TEMP, int8_t AM_OF_SUB, int8_t LUM_INT, int8_t ANGLE>
    constexpr auto pow(const BaseUnit<T, TIME, LENGTH, MASS, EL_CURR, TD_TEMP, AM_OF_SUB, LUM_INT, ANGLE> &unit)
        -> mapped_unit_t<BaseUnit<T, TIME * N, LENGTH * N, MASS * N, EL_CURR * N, TD_TEMP * N, AM_OF_SUB * N, LUM_INT * N, ANGLE * N>> {
        static_assert(N >= 0, "pow supports non-negative exponents; use inv() for reciprocals");
        using Result = mapped_unit_t<BaseUnit<T, TIME * N, LENGTH * N, MASS * N, EL_CURR * N, TD_TEMP * N, AM_OF_SUB * N, LUM_INT * N, ANGLE * N>>;
        T result = 1;
        for (int8_t i = 0; i < N; ++i) {
            result *= unit.value();
        }
        return Result(result);
    }

    template<typename T, int8_t TIME, int8_t LENGTH, int8_t MASS, int8_t EL_CURR, int8_t TD_TEMP, int8_t AM_OF_SUB, int8_t LUM_INT, int8_t ANGLE>
    constexpr auto abs(const BaseUnit<T, TIME, LENGTH, MASS, EL_CURR, TD_TEMP, AM_OF_SUB, LUM_INT, ANGLE> &unit)
        -> mapped_unit_t<BaseUnit<T, TIME, LENGTH, MASS, EL_CURR, TD_TEMP, AM_OF_SUB, LUM_INT, ANGLE>> {
        using Result = mapped_unit_t<BaseUnit<T, TIME, LENGTH, MASS, EL_CURR, TD_TEMP, AM_OF_SUB, LUM_INT, ANGLE>>;
        return Result(unit.value() < 0 ? -unit.value() : unit.value());
    }

    template<typename T, int8_t TIME, int8_t LENGTH, int8_t MASS, int8_t EL_CURR, int8_t TD_TEMP, int8_t AM_OF_SUB, int8_t LUM_INT, int8_t ANGLE>
    constexpr auto min(const BaseUnit<T, TIME, LENGTH, MASS, EL_CURR, TD_TEMP, AM_OF_SUB, LUM_INT, ANGLE> &lhs,
                       const BaseUnit<T, TIME, LENGTH, MASS, EL_CURR, TD_TEMP, AM_OF_SUB, LUM_INT, ANGLE> &rhs)
        -> mapped_unit_t<BaseUnit<T, TIME, LENGTH, MASS, EL_CURR, TD_TEMP, AM_OF_SUB, LUM_INT, ANGLE>> {
        using Result = mapped_unit_t<BaseUnit<T, TIME, LENGTH, MASS, EL_CURR, TD_TEMP, AM_OF_SUB, LUM_INT, ANGLE>>;
        return Result(lhs.value() < rhs.value() ? lhs.value() : rhs.value());
    }

    template<typename T, int8_t TIME, int8_t LENGTH, int8_t MASS, int8_t EL_CURR, int8_t TD_TEMP, int8_t AM_OF_SUB, int8_t LUM_INT, int8_t ANGLE>
    constexpr auto max(const BaseUnit<T, TIME, LENGTH, MASS, EL_CURR, TD_TEMP, AM_OF_SUB, LUM_INT, ANGLE> &lhs,
                       const BaseUnit<T, TIME, LENGTH, MASS, EL_CURR, TD_TEMP, AM_OF_SUB, LUM_INT, ANGLE> &rhs)
        -> mapped_unit_t<BaseUnit<T, TIME, LENGTH, MASS, EL_CURR, TD_TEMP, AM_OF_SUB, LUM_INT, ANGLE>> {
        using Result = mapped_unit_t<BaseUnit<T, TIME, LENGTH, MASS, EL_CURR, TD_TEMP, AM_OF_SUB, LUM_INT, ANGLE>>;
        return Result(lhs.value() < rhs.value() ? rhs.value() : lhs.value());
    }
} // namespace utl

namespace utl {

    // Constants

    constexpr Frequency<double> cesium_hyperfine_freq_d(CAESIUM_HYPERFINE_FREQ_VALUE);
    constexpr Frequency<float> cesium_hyperfine_freq_f(static_cast<float>(CAESIUM_HYPERFINE_FREQ_VALUE));

    constexpr Velocity<double> speed_of_light_d(SPEED_OF_LIGHT_IN_VACUUM_VALUE);
    constexpr Velocity<float> speed_of_light_f(static_cast<float>(SPEED_OF_LIGHT_IN_VACUUM_VALUE));

    constexpr ElectricCharge<float> elementary_charge_f(static_cast<float>(ELEMENTARY_CHARGE_VALUE));
    constexpr ElectricCharge<double> elementary_charge_d(ELEMENTARY_CHARGE_VALUE);

    constexpr MulBaseUnits<float, Energy<float>, Time<float>> planck_constant_f(static_cast<float>(PLANCK_CONSTANT_VALUE));
    constexpr MulBaseUnits<double, Energy<double>, Time<double>> planck_constant_d(PLANCK_CONSTANT_VALUE);

    [[deprecated("use planck_constant_f")]] constexpr auto planc_constant_f = planck_constant_f;
    [[deprecated("use planck_constant_d")]] constexpr auto planc_constant_d = planck_constant_d;

    constexpr DivBaseUnits<float, Energy<float>, ThermodynamicTemperature<float>> boltzmann_constant_f(static_cast<float>(BOLTZMANN_CONSTANT_VALUE));
    constexpr DivBaseUnits<double, Energy<double>, ThermodynamicTemperature<double>> boltzmann_constant_d(
        BOLTZMANN_CONSTANT_VALUE);

    constexpr InvBaseUnit<float, AmountOfSubstance<float>> avogadro_constant_f(static_cast<float>(AVOGADRO_CONSTANT_VALUE));
    constexpr InvBaseUnit<double, AmountOfSubstance<double>> avogadro_constant_d(AVOGADRO_CONSTANT_VALUE);

    constexpr DivBaseUnits<float, LuminousFlux<float>, Power<float>> luminous_efficacy_f(static_cast<float>(LUMINOUS_EFFICACY_VALUE));
    constexpr DivBaseUnits<double, LuminousFlux<double>, Power<double>> luminous_efficacy_d(LUMINOUS_EFFICACY_VALUE);

    // Base Units

    using AmountOfSubstance_f = AmountOfSubstance<float>;
    using AmountOfSubstance_d = AmountOfSubstance<double>;

    using ElectricCurrent_f = ElectricCurrent<float>;
    using ElectricCurrent_d = ElectricCurrent<double>;

    using Length_f = Length<float>;
    using Length_d = Length<double>;

    using LuminousIntensity_f = LuminousIntensity<float>;
    using LuminousIntensity_d = LuminousIntensity<double>;

    using Mass_f = Mass<float>;
    using Mass_d = Mass<double>;

    using ThermodynamicTemperature_f = ThermodynamicTemperature<float>;
    using ThermodynamicTemperature_d = ThermodynamicTemperature<double>;

    using Time_f = Time<float>;
    using Time_d = Time<double>;

    // Derived Units

    using AbsorbedDose_f = AbsorbedDose<float>;
    using AbsorbedDose_d = AbsorbedDose<double>;

    using Acceleration_f = Acceleration<float>;
    using Acceleration_d = Acceleration<double>;

    using Activity_f = Activity<float>;
    using Activity_d = Activity<double>;

    using Angle_f = Angle<float>;
    using Angle_d = Angle<double>;

    using Area_f = Area<float>;
    using Area_d = Area<double>;

    using Capacitance_f = Capacitance<float>;
    using Capacitance_d = Capacitance<double>;

    using CatalyticActivity_f = CatalyticActivity<float>;
    using CatalyticActivity_d = CatalyticActivity<double>;

    using Conductance_f = Conductance<float>;
    using Conductance_d = Conductance<double>;

    using DoseEquivalent_f = DoseEquivalent<float>;
    using DoseEquivalent_d = DoseEquivalent<double>;

    using ElectricCharge_f = ElectricCharge<float>;
    using ElectricCharge_d = ElectricCharge<double>;

    using Energy_f = Energy<float>;
    using Energy_d = Energy<double>;

    using Force_f = Force<float>;
    using Force_d = Force<double>;

    using Frequency_f = Frequency<float>;
    using Frequency_d = Frequency<double>;

    using Illuminance_f = Illuminance<float>;
    using Illuminance_d = Illuminance<double>;

    using Inductance_f = Inductance<float>;
    using Inductance_d = Inductance<double>;

    using LuminousFlux_f = LuminousFlux<float>;
    using LuminousFlux_d = LuminousFlux<double>;

    using MagneticFlux_f = MagneticFlux<float>;
    using MagneticFlux_d = MagneticFlux<double>;

    using MagneticFluxDensity_f = MagneticFluxDensity<float>;
    using MagneticFluxDensity_d = MagneticFluxDensity<double>;

    using Power_f = Power<float>;
    using Power_d = Power<double>;

    using Pressure_f = Pressure<float>;
    using Pressure_d = Pressure<double>;

    using Resistance_f = Resistance<float>;
    using Resistance_d = Resistance<double>;

    using SolidAngle_f = SolidAngle<float>;
    using SolidAngle_d = SolidAngle<double>;

    using Velocity_f = Velocity<float>;
    using Velocity_d = Velocity<double>;

    using Voltage_f = Voltage<float>;
    using Voltage_d = Voltage<double>;

    using Volume_f = Volume<float>;
    using Volume_d = Volume<double>;

} // namespace utl
