#!/usr/bin/env python3
#
# Copyright (C) 2024 Adam Ligocki
# Distributed under MIT licence
#
# Amalgamate the <utl/utl.hpp> include closure into a single header at
# single_include/utl/utl.hpp. Local quoted includes are inlined once (in the
# order the compiler would see them); system includes are de-duplicated and
# hoisted to the top. io.hpp is intentionally excluded, matching utl.hpp (it is
# an opt-in header).
#
# Usage: tools/amalgamate.py [--check]
#   (no args)  regenerate the single header
#   --check    regenerate to a temp buffer and fail if it differs from the
#              committed file (for CI)

import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
INCLUDE_ROOT = os.path.normpath(os.path.join(HERE, "..", "include"))
ROOT = os.path.join(INCLUDE_ROOT, "utl", "utl.hpp")
OUT = os.path.normpath(os.path.join(HERE, "..", "single_include", "utl", "utl.hpp"))

LOCAL_INCLUDE = re.compile(r'^\s*#\s*include\s*"([^"]+)"')
SYSTEM_INCLUDE = re.compile(r'^\s*#\s*include\s*<([^>]+)>')
PRAGMA_ONCE = re.compile(r'^\s*#\s*pragma\s+once')

BANNER = (
    "/*\n"
    " * Copyright (C) 2024 Adam Ligocki\n"
    " * Distributed under MIT licence\n"
    " *\n"
    " * Single-header amalgamation of <utl/utl.hpp>, generated by\n"
    " * tools/amalgamate.py. Do not edit by hand; regenerate instead.\n"
    " */\n\n"
    "#pragma once\n\n"
)


def resolve(include, current_dir):
    for base in (current_dir, INCLUDE_ROOT):
        candidate = os.path.normpath(os.path.join(base, include))
        if os.path.isfile(candidate):
            return candidate
    raise FileNotFoundError("cannot resolve #include \"%s\" from %s" % (include, current_dir))


def strip_leading_license(lines):
    if lines and lines[0].lstrip().startswith("/*"):
        for i, line in enumerate(lines):
            if "*/" in line:
                return lines[i + 1:]
    return lines


def generate():
    visited = set()
    system_includes = []
    body = []

    def process(path):
        real = os.path.normpath(path)
        if real in visited:
            return
        visited.add(real)
        with open(real) as handle:
            lines = strip_leading_license(handle.read().splitlines())
        current_dir = os.path.dirname(real)
        for line in lines:
            if PRAGMA_ONCE.match(line):
                continue
            local = LOCAL_INCLUDE.match(line)
            if local:
                process(resolve(local.group(1), current_dir))
                continue
            system = SYSTEM_INCLUDE.match(line)
            if system:
                if system.group(1) not in system_includes:
                    system_includes.append(system.group(1))
                continue
            body.append(line)

    process(ROOT)

    out = BANNER
    for include in sorted(system_includes):
        out += "#include <%s>\n" % include
    out += "\n"
    collapsed = re.sub(r'\n{3,}', '\n\n', "\n".join(body)).strip()
    return out + collapsed + "\n"


def main():
    content = generate()
    if "--check" in sys.argv[1:]:
        if not os.path.isfile(OUT) or open(OUT).read() != content:
            sys.stderr.write("single_include/utl/utl.hpp is out of date; run tools/amalgamate.py\n")
            return 1
        return 0
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as handle:
        handle.write(content)
    sys.stderr.write("wrote %s\n" % OUT)
    return 0


if __name__ == "__main__":
    sys.exit(main())
